In [2]:
import pandas as pd
from sklearn.feature_selection import VarianceThreshold
from sklearn.preprocessing import LabelEncoder
import os

In [3]:
INPUT_PATH = "D:\Github\Fraud-Sentinel\data\processed\merged_data.csv"
OUTPUT_PATH = "data/processed/clean_data.csv"


def load_data():
    print("Loading merged data...")
    df = pd.read_csv(INPUT_PATH)
    print("Shape:", df.shape)
    return df

<>:1: SyntaxWarning: invalid escape sequence '\G'
<>:1: SyntaxWarning: invalid escape sequence '\G'
C:\Users\Faizan Aziz\AppData\Local\Temp\ipykernel_1720\1680984611.py:1: SyntaxWarning: invalid escape sequence '\G'
  INPUT_PATH = "D:\Github\Fraud-Sentinel\data\processed\merged_data.csv"

In [4]:
df = load_data()

print(df.head())

Loading merged data...
Shape: (590540, 434)
   TransactionID  isFraud  TransactionDT  TransactionAmt ProductCD  card1  \
0        2987000        0          86400            68.5         W  13926
1        2987001        0          86401            29.0         W   2755
2        2987002        0          86469            59.0         W   4663
3        2987003        0          86499            50.0         W  18132
4        2987004        0          86506            50.0         H   4497

   card2  card3       card4  card5  ...                id_31  id_32  \
0    NaN  150.0    discover  142.0  ...                  NaN    NaN
1  404.0  150.0  mastercard  102.0  ...                  NaN    NaN
2  490.0  150.0        visa  166.0  ...                  NaN    NaN
3  567.0  150.0  mastercard  117.0  ...                  NaN    NaN
4  514.0  150.0  mastercard  102.0  ...  samsung browser 6.2   32.0

       id_33           id_34  id_35 id_36 id_37  id_38  DeviceType  \
0        NaN             NaN    NaN   NaN   NaN    NaN         NaN
1        NaN             NaN    NaN   NaN   NaN    NaN         NaN
2        NaN             NaN    NaN   NaN   NaN    NaN         NaN
3        NaN             NaN    NaN   NaN   NaN    NaN         NaN
4  2220x1080  match_status:2      T     F     T      T      mobile

                      DeviceInfo
0                            NaN
1                            NaN
2                            NaN
3                            NaN
4  SAMSUNG SM-G892A Build/NRD90M

[5 rows x 434 columns]

In [5]:
count = 0
threshold = 0.80
for c in df.columns:
    if df[c].isnull().sum()/len(df) > threshold:
        count += 1
        print(f"{c}: Empty percentage: {df[c].isnull().sum() / len(df) * 100:.2f}%")
print(f"Total columns with more than {threshold*100:.0f}% empty values: {count}")

dist2: Empty percentage: 93.63%
D6: Empty percentage: 87.61%
D7: Empty percentage: 93.41%
D8: Empty percentage: 87.31%
D9: Empty percentage: 87.31%
D12: Empty percentage: 89.04%
D13: Empty percentage: 89.51%
D14: Empty percentage: 89.47%
V138: Empty percentage: 86.12%
V139: Empty percentage: 86.12%
V140: Empty percentage: 86.12%
V141: Empty percentage: 86.12%
V142: Empty percentage: 86.12%
V143: Empty percentage: 86.12%
V144: Empty percentage: 86.12%
V145: Empty percentage: 86.12%
V146: Empty percentage: 86.12%
V147: Empty percentage: 86.12%
V148: Empty percentage: 86.12%
V149: Empty percentage: 86.12%
V150: Empty percentage: 86.12%
V151: Empty percentage: 86.12%
V152: Empty percentage: 86.12%
V153: Empty percentage: 86.12%
V154: Empty percentage: 86.12%
V155: Empty percentage: 86.12%
V156: Empty percentage: 86.12%
V157: Empty percentage: 86.12%
V158: Empty percentage: 86.12%
V159: Empty percentage: 86.12%
V160: Empty percentage: 86.12%
V161: Empty percentage: 86.12%
V162: Empty percentage: 86.12%
V163: Empty percentage: 86.12%
V164: Empty percentage: 86.12%
V165: Empty percentage: 86.12%
V166: Empty percentage: 86.12%
V322: Empty percentage: 86.05%
V323: Empty percentage: 86.05%
V324: Empty percentage: 86.05%
V325: Empty percentage: 86.05%
V326: Empty percentage: 86.05%
V327: Empty percentage: 86.05%
V328: Empty percentage: 86.05%
V329: Empty percentage: 86.05%
V330: Empty percentage: 86.05%
V331: Empty percentage: 86.05%
V332: Empty percentage: 86.05%
V333: Empty percentage: 86.05%
V334: Empty percentage: 86.05%
V335: Empty percentage: 86.05%
V336: Empty percentage: 86.05%
V337: Empty percentage: 86.05%
V338: Empty percentage: 86.05%
V339: Empty percentage: 86.05%
id_03: Empty percentage: 88.77%
id_04: Empty percentage: 88.77%
id_07: Empty percentage: 99.13%
id_08: Empty percentage: 99.13%
id_09: Empty percentage: 87.31%
id_10: Empty percentage: 87.31%
id_14: Empty percentage: 86.45%
id_18: Empty percentage: 92.36%
id_21: Empty percentage: 99.13%
id_22: Empty percentage: 99.12%
id_23: Empty percentage: 99.12%
id_24: Empty percentage: 99.20%
id_25: Empty percentage: 99.13%
id_26: Empty percentage: 99.13%
id_27: Empty percentage: 99.12%
id_30: Empty percentage: 86.87%
id_32: Empty percentage: 86.86%
id_33: Empty percentage: 87.59%
id_34: Empty percentage: 86.82%
Total columns with more than 80% empty values: 74

In [6]:
count_dropped = 0
for c in df.columns:
    if df[c].isnull().sum()/len(df) > threshold:
        count_dropped += 1
        df.drop(columns=[c], inplace=True)

print(f"Dropped {count_dropped} columns with more than {threshold*100:.0f}% empty values.")

Dropped 74 columns with more than 80% empty values.

In [7]:
count = 0
threshold = 0.5
for c in df.columns:
    if df[c].isnull().sum()/len(df) > threshold:
        count += 1
        print(f"{c}: Empty percentage: {df[c].isnull().sum() / len(df) * 100:.2f}%")
print(f"Total columns with more than {threshold*100:.0f}% empty values: {count}/{len(df.columns)}")

dist1: Empty percentage: 59.65%
R_emaildomain: Empty percentage: 76.75%
D5: Empty percentage: 52.47%
M5: Empty percentage: 59.35%
M7: Empty percentage: 58.64%
M8: Empty percentage: 58.63%
M9: Empty percentage: 58.63%
V167: Empty percentage: 76.36%
V168: Empty percentage: 76.36%
V169: Empty percentage: 76.32%
V170: Empty percentage: 76.32%
V171: Empty percentage: 76.32%
V172: Empty percentage: 76.36%
V173: Empty percentage: 76.36%
V174: Empty percentage: 76.32%
V175: Empty percentage: 76.32%
V176: Empty percentage: 76.36%
V177: Empty percentage: 76.36%
V178: Empty percentage: 76.36%
V179: Empty percentage: 76.36%
V180: Empty percentage: 76.32%
V181: Empty percentage: 76.36%
V182: Empty percentage: 76.36%
V183: Empty percentage: 76.36%
V184: Empty percentage: 76.32%
V185: Empty percentage: 76.32%
V186: Empty percentage: 76.36%
V187: Empty percentage: 76.36%
V188: Empty percentage: 76.32%
V189: Empty percentage: 76.32%
V190: Empty percentage: 76.36%
V191: Empty percentage: 76.36%
V192: Empty percentage: 76.36%
V193: Empty percentage: 76.36%
V194: Empty percentage: 76.32%
V195: Empty percentage: 76.32%
V196: Empty percentage: 76.36%
V197: Empty percentage: 76.32%
V198: Empty percentage: 76.32%
V199: Empty percentage: 76.36%
V200: Empty percentage: 76.32%
V201: Empty percentage: 76.32%
V202: Empty percentage: 76.36%
V203: Empty percentage: 76.36%
V204: Empty percentage: 76.36%
V205: Empty percentage: 76.36%
V206: Empty percentage: 76.36%
V207: Empty percentage: 76.36%
V208: Empty percentage: 76.32%
V209: Empty percentage: 76.32%
V210: Empty percentage: 76.32%
V211: Empty percentage: 76.36%
V212: Empty percentage: 76.36%
V213: Empty percentage: 76.36%
V214: Empty percentage: 76.36%
V215: Empty percentage: 76.36%
V216: Empty percentage: 76.36%
V217: Empty percentage: 77.91%
V218: Empty percentage: 77.91%
V219: Empty percentage: 77.91%
V220: Empty percentage: 76.05%
V221: Empty percentage: 76.05%
V222: Empty percentage: 76.05%
V223: Empty percentage: 77.91%
V224: Empty percentage: 77.91%
V225: Empty percentage: 77.91%
V226: Empty percentage: 77.91%
V227: Empty percentage: 76.05%
V228: Empty percentage: 77.91%
V229: Empty percentage: 77.91%
V230: Empty percentage: 77.91%
V231: Empty percentage: 77.91%
V232: Empty percentage: 77.91%
V233: Empty percentage: 77.91%
V234: Empty percentage: 76.05%
V235: Empty percentage: 77.91%
V236: Empty percentage: 77.91%
V237: Empty percentage: 77.91%
V238: Empty percentage: 76.05%
V239: Empty percentage: 76.05%
V240: Empty percentage: 77.91%
V241: Empty percentage: 77.91%
V242: Empty percentage: 77.91%
V243: Empty percentage: 77.91%
V244: Empty percentage: 77.91%
V245: Empty percentage: 76.05%
V246: Empty percentage: 77.91%
V247: Empty percentage: 77.91%
V248: Empty percentage: 77.91%
V249: Empty percentage: 77.91%
V250: Empty percentage: 76.05%
V251: Empty percentage: 76.05%
V252: Empty percentage: 77.91%
V253: Empty percentage: 77.91%
V254: Empty percentage: 77.91%
V255: Empty percentage: 76.05%
V256: Empty percentage: 76.05%
V257: Empty percentage: 77.91%
V258: Empty percentage: 77.91%
V259: Empty percentage: 76.05%
V260: Empty percentage: 77.91%
V261: Empty percentage: 77.91%
V262: Empty percentage: 77.91%
V263: Empty percentage: 77.91%
V264: Empty percentage: 77.91%
V265: Empty percentage: 77.91%
V266: Empty percentage: 77.91%
V267: Empty percentage: 77.91%
V268: Empty percentage: 77.91%
V269: Empty percentage: 77.91%
V270: Empty percentage: 76.05%
V271: Empty percentage: 76.05%
V272: Empty percentage: 76.05%
V273: Empty percentage: 77.91%
V274: Empty percentage: 77.91%
V275: Empty percentage: 77.91%
V276: Empty percentage: 77.91%
V277: Empty percentage: 77.91%
V278: Empty percentage: 77.91%
id_01: Empty percentage: 75.58%
id_02: Empty percentage: 76.15%
id_05: Empty percentage: 76.82%
id_06: Empty percentage: 76.82%
id_11: Empty percentage: 76.13%
id_12: Empty percentage: 75.58%
id_13: Empty percentage: 78.44%
id_15: Empty percentage: 76.13%
id_16: Empty percentage: 78.10%
id_17: Empty percentage: 76.40%
id_19: Empty percentage: 76.41%
id_20: Empty percentage: 76.42%
id_28: Empty percentage: 76.13%
id_29: Empty percentage: 76.13%
id_31: Empty percentage: 76.25%
id_35: Empty percentage: 76.13%
id_36: Empty percentage: 76.13%
id_37: Empty percentage: 76.13%
id_38: Empty percentage: 76.13%
DeviceType: Empty percentage: 76.16%
DeviceInfo: Empty percentage: 79.91%
Total columns with more than 50% empty values: 140/360

In [8]:
# Fill missing values:
# - Numerical (int/float) → median
# - Categorical (object) → "missing"

for col in df.columns:
    if df[col].dtype in ["int64", "float64"]:
        df[col] = df[col].fillna(df[col].median())
    else:
        df[col] = df[col].fillna("missing")

print("Missing values handled!")

Missing values handled!

In [9]:
any(df.isnull().sum() > 0)

False

In [10]:
for c in (df.columns):
    print(c)

TransactionID
isFraud
TransactionDT
TransactionAmt
ProductCD
card1
card2
card3
card4
card5
card6
addr1
addr2
dist1
P_emaildomain
R_emaildomain
C1
C2
C3
C4
C5
C6
C7
C8
C9
C10
C11
C12
C13
C14
D1
D2
D3
D4
D5
D10
D11
D15
M1
M2
M3
M4
M5
M6
M7
M8
M9
V1
V2
V3
V4
V5
V6
V7
V8
V9
V10
V11
V12
V13
V14
V15
V16
V17
V18
V19
V20
V21
V22
V23
V24
V25
V26
V27
V28
V29
V30
V31
V32
V33
V34
V35
V36
V37
V38
V39
V40
V41
V42
V43
V44
V45
V46
V47
V48
V49
V50
V51
V52
V53
V54
V55
V56
V57
V58
V59
V60
V61
V62
V63
V64
V65
V66
V67
V68
V69
V70
V71
V72
V73
V74
V75
V76
V77
V78
V79
V80
V81
V82
V83
V84
V85
V86
V87
V88
V89
V90
V91
V92
V93
V94
V95
V96
V97
V98
V99
V100
V101
V102
V103
V104
V105
V106
V107
V108
V109
V110
V111
V112
V113
V114
V115
V116
V117
V118
V119
V120
V121
V122
V123
V124
V125
V126
V127
V128
V129
V130
V131
V132
V133
V134
V135
V136
V137
V167
V168
V169
V170
V171
V172
V173
V174
V175
V176
V177
V178
V179
V180
V181
V182
V183
V184
V185
V186
V187
V188
V189
V190
V191
V192
V193
V194
V195
V196
V197
V198
V199
V200
V201
V202
V203
V204
V205
V206
V207
V208
V209
V210
V211
V212
V213
V214
V215
V216
V217
V218
V219
V220
V221
V222
V223
V224
V225
V226
V227
V228
V229
V230
V231
V232
V233
V234
V235
V236
V237
V238
V239
V240
V241
V242
V243
V244
V245
V246
V247
V248
V249
V250
V251
V252
V253
V254
V255
V256
V257
V258
V259
V260
V261
V262
V263
V264
V265
V266
V267
V268
V269
V270
V271
V272
V273
V274
V275
V276
V277
V278
V279
V280
V281
V282
V283
V284
V285
V286
V287
V288
V289
V290
V291
V292
V293
V294
V295
V296
V297
V298
V299
V300
V301
V302
V303
V304
V305
V306
V307
V308
V309
V310
V311
V312
V313
V314
V315
V316
V317
V318
V319
V320
V321
id_01
id_02
id_05
id_06
id_11
id_12
id_13
id_15
id_16
id_17
id_19
id_20
id_28
id_29
id_31
id_35
id_36
id_37
id_38
DeviceType
DeviceInfo

In [11]:
df = df.drop(["TransactionID", "TransactionDT"], axis=1, errors="ignore")

In [12]:
df.head()

,isFraud,TransactionAmt,ProductCD,card1,card2,card3,card4,card5,card6,addr1,...,id_20,id_28,id_29,id_31,id_35,id_36,id_37,id_38,DeviceType,DeviceInfo
0,0,68.5,W,13926,361.0,150.0,discover,142.0,credit,315.0,...,472.0,missing,missing,missing,missing,missing,missing,missing,missing,missing
1,0,29.0,W,2755,404.0,150.0,mastercard,102.0,credit,325.0,...,472.0,missing,missing,missing,missing,missing,missing,missing,missing,missing
2,0,59.0,W,4663,490.0,150.0,visa,166.0,debit,330.0,...,472.0,missing,missing,missing,missing,missing,missing,missing,missing,missing
3,0,50.0,W,18132,567.0,150.0,mastercard,117.0,debit,476.0,...,472.0,missing,missing,missing,missing,missing,missing,missing,missing,missing
4,0,50.0,H,4497,514.0,150.0,mastercard,102.0,credit,420.0,...,144.0,New,NotFound,samsung browser 6.2,T,F,T,T,mobile,SAMSUNG SM-G892A Build/NRD90M

In [13]:
for col in df.select_dtypes(include="object").columns:
    le = LabelEncoder()
    df[col] = le.fit_transform(df[col].astype(str))

print("Encoding done!")

Encoding done!

In [15]:
data=df.describe()

In [ ]:
data.to_csv("dataframe.csv", index=False)

,isFraud,TransactionAmt,ProductCD,card1,card2,card3,card4,card5,card6,addr1,...,id_20,id_28,id_29,id_31,id_35,id_36,id_37,id_38,DeviceType,DeviceInfo
count,590540.000000,590540.000000,590540.000000,590540.000000,590540.000000,590540.000000,590540.000000,590540.000000,590540.000000,590540.000000,...,590540.000000,590540.000000,590540.000000,590540.000000,590540.000000,590540.000000,590540.000000,590540.000000,590540.000000,590540.000000
mean,0.034990,135.027176,3.220757,9898.734658,362.531959,153.186458,3.266305,199.471611,1.753033,291.653527,...,455.936587,1.632184,1.634396,89.922168,1.654289,1.534238,1.709557,1.636084,0.950012,1663.024449
std,0.183755,239.162522,1.423926,4901.170153,156.595356,11.322604,1.035866,41.157610,0.449543,95.949345,...,79.347430,0.700504,0.696917,16.834543,0.663430,0.838376,0.556321,0.694144,0.485741,239.984507
min,0.000000,0.251000,0.000000,1000.000000,100.000000,100.000000,0.000000,100.000000,0.000000,100.000000,...,100.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,0.000000,43.321000,3.000000,6019.000000,215.000000,150.000000,2.000000,166.000000,1.000000,205.000000,...,472.000000,2.000000,2.000000,96.000000,2.000000,2.000000,2.000000,2.000000,1.000000,1735.000000
50%,0.000000,68.769000,4.000000,9678.000000,361.000000,150.000000,4.000000,226.000000,2.000000,299.000000,...,472.000000,2.000000,2.000000,96.000000,2.000000,2.000000,2.000000,2.000000,1.000000,1735.000000
75%,0.000000,125.000000,4.000000,14184.000000,512.000000,150.000000,4.000000,226.000000,2.000000,327.000000,...,472.000000,2.000000,2.000000,96.000000,2.000000,2.000000,2.000000,2.000000,1.000000,1735.000000
max,1.000000,31937.391000,4.000000,18396.000000,600.000000,231.000000,4.000000,237.000000,4.000000,540.000000,...,661.000000,2.000000,2.000000,130.000000,2.000000,2.000000,2.000000,2.000000,2.000000,1786.000000